### Numpy - Numerical Python

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(5,)

In [7]:
array1.ndim

1

In [12]:
array2 =np.array ([[1,2,3,4,5],[6,7,8,9,10]])

In [13]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
array2.shape

(2, 5)

In [16]:
array2.ndim

2

In [22]:
# we can specify the datatype of the array by using the dtype option
array3 = np.array([[1.2,2.2,3.3],[1.1,2.4,3.3]],dtype= float)

In [23]:
array3

array([[1.2, 2.2, 3.3],
       [1.1, 2.4, 3.3]])

In [24]:
array3.shape

(2, 3)

In [25]:
array4 = np.array([[1,2,3],[4,5,6]],dtype=float)

In [26]:
array4

array([[1., 2., 3.],
       [4., 5., 6.]])

#### While reshaping an array the operation goes element wise from the rows.

In [ ]:
# For ex [1,2,3,4,5,6] is reshaped to (3,2) then it will start with ((1,2)(3,4)(5,6))

In [30]:
# To reshape an array
array5=array4.reshape(3,2)

In [31]:
array5.shape

(3, 2)

In [32]:
array_zero=np.zeros(8)

In [33]:
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
array_ones=np.ones([3,3],dtype=int)

In [38]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### Creating an array with existing data

In [39]:
x1 = ([3,4],[5,4],[6,7])

In [40]:
a1 = np.asarray(x1,dtype=float)

In [41]:
type(x1)

([3, 4], [5, 4], [6, 7])

In [42]:
a1

array([[3., 4.],
       [5., 4.],
       [6., 7.]])

### Array from numerical ranges

In [43]:
a1 = np.arange(0,20,3)
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [46]:
# including starting & ending values, if we want to divide into n equal parts
a2 = np.linspace(10,20,5)

In [45]:
a2

array([10. , 12.5, 15. , 17.5, 20. ])

### Array Slicing

In [50]:
a5=np.arange(10)
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
slice1=slice(2,9,2)

In [54]:
a5[slice1]

array([2, 4, 6, 8])

In [55]:
slice2=slice(2,9)

In [56]:
a5[slice2]

array([2, 3, 4, 5, 6, 7, 8])

In [57]:
# The above slicing operation can be done as below as well
a5[2:9]

array([2, 3, 4, 5, 6, 7, 8])

### Integer Indexing

In [3]:
#
a = np.array([[1,2],[3,4],[5,6]])

In [10]:
# In this example first [0,1,2] refers to rows index and second [0,1,0] refers to column index
b = a[[0,1,2],[0,1,0]]

In [5]:
b

array([1, 4, 5])

In [6]:
arr4_3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [7]:
arr4_3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr_index = arr4_3[1:4,1:3]

In [9]:
arr_index

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [11]:
arr4_3[1:,1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [12]:
arr12=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])

In [13]:
arr12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
arr5_5=arr12.reshape([5,5])

In [16]:
arr5_5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr5_5[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [18]:
arr5_5[:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [19]:
a = np.array([1,5,np.nan,8,np.nan,52,65,np.nan])

In [20]:
a

array([ 1.,  5., nan,  8., nan, 52., 65., nan])

In [22]:
a[~np.isnan(a)]

array([ 1.,  5.,  8., 52., 65.])

#### Broadcasting

In [4]:
x= np.array([1,2,3,4])
y=np.array([6,7,8,9])



In [5]:
z = x*y

In [6]:
z

array([ 6, 14, 24, 36])

In [7]:
s=5
s1 = x * 5

In [8]:
s1

array([ 5, 10, 15, 20])

In [11]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])

a3 = a1 * a2
a3

array([[ 7, 16, 27],
       [40, 55, 72]])

In [12]:
a4 = np.array([[1,2,3],[4,5,6]])
a5 = 5

a6 = a4 * a5

In [13]:
a6

array([[ 5, 10, 15],
       [20, 25, 30]])

In [14]:
a7 = np.array([[1,2,3],[4,5,6]])
a8 = np.array([5,5,5])

In [15]:
a9 = a7 * a8
a9

array([[ 5, 10, 15],
       [20, 25, 30]])

In [16]:
a10 = np.arange(12)

In [17]:
a10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
a11 = a10.reshape([3,4])

In [20]:
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
# Transpose = to convert rows into columns
a11.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
array14 = np.arange(8).reshape(4,2)

In [23]:
array14

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [28]:
# array flatten

a15=array14.flatten()

In [29]:
a15

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
b1 = np.arange(6).reshape(3,2)

In [33]:
b2 = np.arange(7,13).reshape(3,2)

In [36]:
b1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
# Concatenate
np.concatenate([b1,b2])

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
#Stack
(np.stack((b1,b2)))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [45]:
np.stack((b1,b2),axis=0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [48]:
(np.stack((b1,b2),axis=1))

array([[[ 0,  1],
        [ 7,  8]],

       [[ 2,  3],
        [ 9, 10]],

       [[ 4,  5],
        [11, 12]]])

In [49]:
np.shape((np.stack((b1,b2),axis=1)))

(3, 2, 2)

In [50]:
np.shape((np.stack((b1,b2),axis=0)))

(2, 3, 2)

In [52]:

np.vstack((b1,b2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
np.hstack((b1,b2))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [54]:
b3 = np.arange(9)
np.split(b3,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [57]:
b4 = np.arange(6).reshape(3,2)
b5=np.arange(7,13).reshape(3,2)

In [58]:
b5

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [59]:
b6=np.append(b4,b5,axis=0)

In [60]:
b6

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [61]:
b7=np.append(b4,b5,axis=1)

In [62]:
b7

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [65]:
np.append?


In [66]:
b8 = np.append(b4,b5)

In [67]:
b8

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12])

#### Insert 

In [68]:
np.insert?

In [69]:
c1 = np.arange(9).reshape(3,3)

In [70]:
c1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.insert(c1,1,5)

array([0, 5, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.insert(c1,1,5,axis=0)

array([[0, 1, 2],
       [5, 5, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
np.insert(c1,1,5,axis=1)

array([[0, 5, 1, 2],
       [3, 5, 4, 5],
       [6, 5, 7, 8]])

#### delete

In [76]:
np.delete?


In [77]:
c1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
c2 = np.insert(c1,1,5,axis=0)

In [79]:
c2

array([[0, 1, 2],
       [5, 5, 5],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
c3 = np.delete(c2,1,axis=0)

In [81]:
c3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
c4=np.array([10,10,20,30,40,0])

np.unique(c4)

array([ 0, 10, 20, 30, 40])

In [83]:
np.add?

In [84]:
d1 = np.arange(6).reshape(3,2)
d2 = np.arange(7,13).reshape(3,2)

In [86]:
d1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
d2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
np.add(d1,d2)

array([[ 7,  9],
       [11, 13],
       [15, 17]])

In [88]:
np.add(d1,5)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [89]:
np.subtract(d2,5)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [90]:
np.multiply(d1,100)

array([[  0, 100],
       [200, 300],
       [400, 500]])

In [91]:
np.multiply(d1,d2)

array([[ 0,  8],
       [18, 30],
       [44, 60]])

In [92]:
np.divide(d2,d1)

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_12296/680826057.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(d2,d1)


array([[       inf, 8.        ],
       [4.5       , 3.33333333],
       [2.75      , 2.4       ]])

In [93]:
np.power(d1,2)

array([[ 0,  1],
       [ 4,  9],
       [16, 25]], dtype=int32)

In [94]:
np.add(d1,[100,200])

array([[100, 201],
       [102, 203],
       [104, 205]])

In [95]:
d1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [96]:
np.percentile(d1,50,axis=1)

array([0.5, 2.5, 4.5])

In [101]:
np.percentile(d1,50,axis=0)

array([2., 3.])

In [102]:
d1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [98]:
np.mean(d1)

2.5

In [99]:
np.mean(d1,axis=0)

array([2., 3.])

In [100]:
np.mean(d1,axis=1)

array([0.5, 2.5, 4.5])

In [103]:
np.median(d1)

2.5

In [104]:
np.median(d1,axis=0)

array([2., 3.])

In [105]:
np.median(d1,axis=1)

array([0.5, 2.5, 4.5])

In [106]:
np.std?


In [107]:
np.std(d1)

1.707825127659933

In [108]:
np.std(d1,axis=0)

array([1.63299316, 1.63299316])

### Pandas

In [109]:
import pandas as pd

In [110]:
a = np.array([10,20,2,40])

In [112]:
type(a)

numpy.ndarray

In [113]:
s = pd.Series(a)

In [114]:
s

0    10
1    20
2     2
3    40
dtype: int32

In [136]:
s0=pd.Series(a,index=[10,20,30,40])

In [137]:
s0

10    10
20    20
30     2
40    40
dtype: int32

In [115]:
type(s)

pandas.core.series.Series

In [116]:
b1 = np.arange(6).reshape(3,2)

In [117]:
b1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [133]:
s1=pd.Series(b1)

ValueError: Data must be 1-dimensional

In [134]:
s2 = pd.Series(a,index=200)

TypeError: Index(...) must be called with a collection of some kind, 200 was passed

In [121]:
pd.Series?

In [122]:
dict1={1:"value1",2:"value2",3:"value3"}

In [123]:
s4=pd.Series(dict1)

In [124]:
s4

1    value1
2    value2
3    value3
dtype: object

In [126]:
dict2={'a':"abc",'b':"def",'c':"ghi"}

In [139]:
s5=pd.Series(dict2,index=('a','b','c'))

In [140]:
s5

a    abc
b    def
c    ghi
dtype: object

In [141]:
list1=[20,30,40,50]

In [142]:
pd.Series(a,index=list1)

20    10
30    20
40     2
50    40
dtype: int32