1.	Create a 2D array and print the dim and shape

In [11]:
import numpy as np

In [15]:
array1 = np.array([["alex","arjun","arya"],["babu","bala","baskar"]])

In [20]:
# To Print the shape of the array. The returned output is in (#No of Rows , #No of Columns)
array1.shape

(2, 3)

In [17]:
# To Print the number of dimensions in the array, Usually we use only 1 or 2 dimensional arrays in most of our use cases
array1.ndim

2

In [19]:
array1

array([['alex', 'arjun', 'arya'],
       ['babu', 'bala', 'baskar']], dtype='<U6')

2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [21]:
array_20=np.array(np.arange(20))

In [22]:
array_20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
# Option 1
# We can slice the values in the array using the slice funtion, it takes in three arguments Slice(Start, < End, Step size)
slice1=slice(10,16)
array_20[slice1]

array([10, 11, 12, 13, 14, 15])

In [24]:
# Option 2
# we can also slice an array using the : operator
array_20[10:16]

array([10, 11, 12, 13, 14, 15])

3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using

a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [40]:
# array1
# Option 1: We can create n dimensional arrays using the np.full function 
array_3=np.full((7,5),5)

In [35]:
array_3

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [42]:
# array2 
# Option 2: We can create n dimensional arrays using the np.arange chained with reshapr function
# Opton 3 : We can also make use of the np.random.random function

array_4 = np.arange(35).reshape(7,5)
array_4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [51]:
array_5 = np.random.random((7,5))

In [47]:
array_5

array([[0.59920946, 0.46077522, 0.60824081, 0.81373489, 0.95523308],
       [0.28209082, 0.79985278, 0.68168466, 0.57808996, 0.08848347],
       [0.95280021, 0.27593383, 0.85351598, 0.55047226, 0.14274619],
       [0.40042607, 0.85225046, 0.82774393, 0.36965101, 0.2775073 ],
       [0.37331365, 0.55725871, 0.27665444, 0.38764641, 0.46121723],
       [0.94457174, 0.8025895 , 0.01988568, 0.46444027, 0.25926217],
       [0.10546442, 0.94412282, 0.37891016, 0.72568612, 0.06765977]])

In [52]:
array_add=array_3 + array_4

In [53]:
array_add

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [54]:
array_sub=array_3 - array_4

In [55]:
array_sub

array([[  5,   4,   3,   2,   1],
       [  0,  -1,  -2,  -3,  -4],
       [ -5,  -6,  -7,  -8,  -9],
       [-10, -11, -12, -13, -14],
       [-15, -16, -17, -18, -19],
       [-20, -21, -22, -23, -24],
       [-25, -26, -27, -28, -29]])

In [56]:
array_mul=array_3 * array_4

In [57]:
array_mul

array([[  0,   5,  10,  15,  20],
       [ 25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70],
       [ 75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170]])

In [58]:
array_div=array_3 / array_4

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_4720/1488732019.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_div=array_3 / array_4


In [72]:
array_div1=np.divide(array_3,array_4)

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_4720/4146037818.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_div1=np.divide(array_3,array_4)


In [73]:
array_div1

array([[       inf, 5.        , 2.5       , 1.66666667, 1.25      ],
       [1.        , 0.83333333, 0.71428571, 0.625     , 0.55555556],
       [0.5       , 0.45454545, 0.41666667, 0.38461538, 0.35714286],
       [0.33333333, 0.3125    , 0.29411765, 0.27777778, 0.26315789],
       [0.25      , 0.23809524, 0.22727273, 0.2173913 , 0.20833333],
       [0.2       , 0.19230769, 0.18518519, 0.17857143, 0.17241379],
       [0.16666667, 0.16129032, 0.15625   , 0.15151515, 0.14705882]])

In [59]:
array_div

array([[       inf, 5.        , 2.5       , 1.66666667, 1.25      ],
       [1.        , 0.83333333, 0.71428571, 0.625     , 0.55555556],
       [0.5       , 0.45454545, 0.41666667, 0.38461538, 0.35714286],
       [0.33333333, 0.3125    , 0.29411765, 0.27777778, 0.26315789],
       [0.25      , 0.23809524, 0.22727273, 0.2173913 , 0.20833333],
       [0.2       , 0.19230769, 0.18518519, 0.17857143, 0.17241379],
       [0.16666667, 0.16129032, 0.15625   , 0.15151515, 0.14705882]])

4.	Create 2 incompatible arrays for broadcast and print out the error

In [60]:
array_12=np.full((2,3),4)

In [61]:
array_12

array([[4, 4, 4],
       [4, 4, 4]])

In [62]:
array_13=np.arange(6).reshape(3,2)

In [63]:
array_13

array([[0, 1],
       [2, 3],
       [4, 5]])

In [64]:
array_incomp=array_12 + array_13 

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### Question 5 & 6
5.	Create two arrays of any dimension and perform vstack and hstack
6.	Append two arrays using axis = 0 and axis = 1

We have combined both the tasks in the following example

In [65]:
array_a=np.full((3,3),5)

In [75]:
array_b=np.full((3,3),10)

In [76]:
# vstack stacks the data in the array in the rows, vertically .so it is called as vstack(vertical stack)
np.vstack((array_a,array_b))

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [ 5,  5,  5],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [80]:
# vstack is equivalent to appending the array in the axis=0
np.append(array_a,array_b,axis=0)

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [ 5,  5,  5],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [77]:
# hstack stacks the data in the array in the columns, horizontally .so it is called as hstack(horizontal stack)
np.hstack((array_a,array_b))

array([[ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10]])

In [79]:
# hstack is equivalent to appending the array in the axis=1
np.append(array_a,array_b,axis=1)

array([[ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10]])

7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [82]:
import pandas as pd

In [89]:
df1 = pd.DataFrame([["Alex",34,"Chennai",20000],["Arjun",31,"Chennai",27000],["Abraham",31,"Madurai",21000],["Balu",34,"Chennai",18000],["Babu",29,"Hyderabad",20000],["Baskar",27,"Hyderabad",22000],["Dinesh",26,"Cochin",29000],["Divya",26,"Cochin",28000],["Divakar",29,"Hyderabad",27500]],columns=["Name","Age","Location","Salary"]) 

In [90]:
df1

Name  Age   Location  Salary
0     Alex   34    Chennai   20000
1    Arjun   31    Chennai   27000
2  Abraham   31    Madurai   21000
3     Balu   34    Chennai   18000
4     Babu   29  Hyderabad   20000
5   Baskar   27  Hyderabad   22000
6   Dinesh   26     Cochin   29000
7    Divya   26     Cochin   28000
8  Divakar   29  Hyderabad   27500

8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [92]:
dict1={"name":["ajay","ashok","arvind","arya"],"maths":[45,55,56,88],"english":[54,65,59,66],"science":[85,95,60,91],"history":[49,59,66,88],"computer":[75,52,61,68],"biology":[56,58,56,65],"tamil":[77,43,81,85]}

In [93]:
df2=pd.DataFrame(dict1)

In [94]:
df2

name  maths  english  science  history  computer  biology  tamil
0    ajay     45       54       85       49        75       56     77
1   ashok     55       65       95       59        52       58     43
2  arvind     56       59       60       66        61       56     81
3    arya     88       66       91       88        68       65     85

9.	Use loc and iloc to subset the data for the above dataframe

In [100]:
df1.loc[:3,["Name","Age"]]

Name  Age
0     Alex   34
1    Arjun   31
2  Abraham   31
3     Balu   34

In [102]:
#loc uses the index values for the rows and labels for the columns
df1.loc[2:8,["Name","Age","Location"]]

Name  Age   Location
2  Abraham   31    Madurai
3     Balu   34    Chennai
4     Babu   29  Hyderabad
5   Baskar   27  Hyderabad
6   Dinesh   26     Cochin
7    Divya   26     Cochin
8  Divakar   29  Hyderabad

In [109]:
# iloc uses the index values for both the row and column values
df2.iloc[:,0:3]

name  maths  english
0    ajay     45       54
1   ashok     55       65
2  arvind     56       59
3    arya     88       66

In [111]:
df2.iloc[1:4,0:6]

name  maths  english  science  history  computer
1   ashok     55       65       95       59        52
2  arvind     56       59       60       66        61
3    arya     88       66       91       88        68

10.	How to check the total number of not null values in a column?

In [114]:
# let us add some null values to the existing dataframe

dept=["HR","Sales",np.nan,np.nan,"HR","Marketing","HR","Sales",np.nan]

In [115]:
df1["Department"]=dept

In [116]:
df1

Name  Age   Location  Salary Department
0     Alex   34    Chennai   20000         HR
1    Arjun   31    Chennai   27000      Sales
2  Abraham   31    Madurai   21000        NaN
3     Balu   34    Chennai   18000        NaN
4     Babu   29  Hyderabad   20000         HR
5   Baskar   27  Hyderabad   22000  Marketing
6   Dinesh   26     Cochin   29000         HR
7    Divya   26     Cochin   28000      Sales
8  Divakar   29  Hyderabad   27500        NaN

In [124]:
# To check the column null values count
df1["Department"].isnull().sum()

3

11.	Create a dataframe with missing values and fill them all with 100

In [125]:
df3=pd.DataFrame([["Alex",np.nan],["Arjun",100],["Babu",np.nan],["Dinesh",190],["Oscar",210]],columns=["Name","Score"])

In [126]:
df3

Name  Score
0    Alex    NaN
1   Arjun  100.0
2    Babu    NaN
3  Dinesh  190.0
4   Oscar  210.0

In [129]:
# we can make use of the fillna method to fill null/nan values
df3["Score"]=df3["Score"].fillna(100)

In [130]:
df3

Name  Score
0    Alex  100.0
1   Arjun  100.0
2    Babu  100.0
3  Dinesh  190.0
4   Oscar  210.0

12.	Create a dataframe with missing values and drop the null records

In [136]:
df4=pd.DataFrame([["Alex",np.nan],["Arjun",100],["Babu",np.nan],["Dinesh",190],["Oscar",210]],columns=["Name","Score"])

In [132]:
df4

Name  Score
0    Alex    NaN
1   Arjun  100.0
2    Babu    NaN
3  Dinesh  190.0
4   Oscar  210.0

In [134]:
# This command will remove the rows which contains atleast 1 null value in the rows
df4=df4.dropna()

In [135]:
df4

Name  Score
1   Arjun  100.0
3  Dinesh  190.0
4   Oscar  210.0

In [138]:
df4=df4.dropna(subset=["Score"])

In [139]:
df4

Name  Score
1   Arjun  100.0
3  Dinesh  190.0
4   Oscar  210.0

13.	Perform following aggregation task on below table
a.	Get the average age group by Regrion
b.	Get the sum of Age and Validation group by Hair color and then reset the index
c.	Get the man and the median of Age group by Region


In [141]:
# Let us use the pandas read_csv to load the data into a dataframe 
df4=pd.read_csv(r"C:\Users\ADMIN\Desktop\assignment.csv")

In [142]:
df4

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [146]:
# Average age Group by region
df4.groupby(["U.S. Region"])["Age"].agg([np.mean])

mean
U.S. Region           
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143

In [149]:
df4.groupby(["U.S. Region"])["Age"].mean()

U.S. Region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: Age, dtype: float64

b. Get the sum of Age and Validation group by Hair color and then reset the index 

In [151]:
df4.groupby(["Hair Color"])[["Age","Validation"]].sum().reset_index()

Hair Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

c.	Get the mean and the median of Age group by Region

In [153]:
df4.groupby(["U.S. Region"])["Age"].agg([np.mean,np.median])

mean  median
U.S. Region                   
Northeast    32.750000    31.0
Northwest    40.500000    40.5
Southeast    31.000000    25.5
Southwest    29.857143    25.0

14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [156]:
# We can first split the original table into two tables with the help of Pandas slicing operation
df5=df4[:9]

In [157]:
df5

Age Hair Color U.S. Region  Validation
0   25      Black   Southwest           1
1   30      Black   Northwest           1
2   45        Red   Northeast           1
3   35      Blond   Southwest           0
4   33      Brown   Southwest           0
5   35      Brown   Northeast           0
6   25      Black   Southwest           0
7   52      Brown   Southeast           0
8   21      Blond   Southwest           1

In [158]:
df6=df4[9:]

In [159]:
df6

Age Hair Color U.S. Region  Validation
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [160]:
pd.merge(df5,df6,on='U.S. Region')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      35        Blond   Southwest             0     48        Black   
3      35        Blond   Southwest             0     22        Black   
4      33        Brown   Southwest             0     48        Black   
5      33        Brown   Southwest             0     22        Black   
6      25        Black   Southwest             0     48        Black   
7      25        Black   Southwest             0     22        Black   
8      21        Blond   Southwest             1     48        Black   
9      21        Blond   Southwest             1     22        Black   
10     30        Black   Northwest             1     51        Black   
11     45          Red   Northeast             1     24        Blond   
12     45          Red   Northeast             1     27        Brown   
13     35        Brown   Northeast             0     24        Blond   
14     35        Brown   Northeast             0     27        Brown   
15     52        Brown   Southeast             0     28        Black   
16     52        Brown   Southeast             0     21        Blond   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

In [162]:
df5.merge(df6,on='U.S. Region',how='left')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      30        Black   Northwest             1     51        Black   
3      45          Red   Northeast             1     24        Blond   
4      45          Red   Northeast             1     27        Brown   
5      35        Blond   Southwest             0     48        Black   
6      35        Blond   Southwest             0     22        Black   
7      33        Brown   Southwest             0     48        Black   
8      33        Brown   Southwest             0     22        Black   
9      35        Brown   Northeast             0     24        Blond   
10     35        Brown   Northeast             0     27        Brown   
11     25        Black   Southwest             0     48        Black   
12     25        Black   Southwest             0     22        Black   
13     52        Brown   Southeast             0     28        Black   
14     52        Brown   Southeast             0     21        Blond   
15     52        Brown   Southeast             0     23        Brown   
16     21        Blond   Southwest             1     48        Black   
17     21        Blond   Southwest             1     22        Black   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              0  
5              1  
6              0  
7              1  
8              0  
9              0  
10             0  
11             1  
12             0  
13             1  
14             1  
15             1  
16             1  
17             0

In [163]:
df5.merge(df6,on='U.S. Region',how='right')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      45          Red   Northeast             1     24        Blond   
1      35        Brown   Northeast             0     24        Blond   
2      25        Black   Southwest             1     48        Black   
3      35        Blond   Southwest             0     48        Black   
4      33        Brown   Southwest             0     48        Black   
5      25        Black   Southwest             0     48        Black   
6      21        Blond   Southwest             1     48        Black   
7      25        Black   Southwest             1     22        Black   
8      35        Blond   Southwest             0     22        Black   
9      33        Brown   Southwest             0     22        Black   
10     25        Black   Southwest             0     22        Black   
11     21        Blond   Southwest             1     22        Black   
12     45          Red   Northeast             1     27        Brown   
13     35        Brown   Northeast             0     27        Brown   
14     52        Brown   Southeast             0     28        Black   
15     52        Brown   Southeast             0     21        Blond   
16     30        Black   Northwest             1     51        Black   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              0  
1              0  
2              1  
3              1  
4              1  
5              1  
6              1  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1

In [164]:
df5.merge(df6,on='U.S. Region',how='inner')

Age_x Hair Color_x U.S. Region  Validation_x  Age_y Hair Color_y  \
0      25        Black   Southwest             1     48        Black   
1      25        Black   Southwest             1     22        Black   
2      35        Blond   Southwest             0     48        Black   
3      35        Blond   Southwest             0     22        Black   
4      33        Brown   Southwest             0     48        Black   
5      33        Brown   Southwest             0     22        Black   
6      25        Black   Southwest             0     48        Black   
7      25        Black   Southwest             0     22        Black   
8      21        Blond   Southwest             1     48        Black   
9      21        Blond   Southwest             1     22        Black   
10     30        Black   Northwest             1     51        Black   
11     45          Red   Northeast             1     24        Blond   
12     45          Red   Northeast             1     27        Brown   
13     35        Brown   Northeast             0     24        Blond   
14     35        Brown   Northeast             0     27        Brown   
15     52        Brown   Southeast             0     28        Black   
16     52        Brown   Southeast             0     21        Blond   
17     52        Brown   Southeast             0     23        Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

15.	Split the below table and perform concat row wise and column wise



In [166]:
# Concat default is row wise concatenation
pd.concat([df5,df6],ignore_index=True)

Age Hair Color U.S. Region  Validation
0    25      Black   Southwest           1
1    30      Black   Northwest           1
2    45        Red   Northeast           1
3    35      Blond   Southwest           0
4    33      Brown   Southwest           0
5    35      Brown   Northeast           0
6    25      Black   Southwest           0
7    52      Brown   Southeast           0
8    21      Blond   Southwest           1
9    24      Blond   Northeast           0
10   48      Black   Southwest           1
11   22      Black   Southwest           0
12   27      Brown   Northeast           0
13   28      Black   Southeast           1
14   21      Blond   Southeast           1
15   51      Black   Northwest           0
16   23      Brown   Southeast           1

In [169]:
pd.concat([df5,df6],axis=1)

Age Hair Color U.S. Region  Validation   Age Hair Color U.S. Region  \
0   25.0      Black   Southwest         1.0   NaN        NaN         NaN   
1   30.0      Black   Northwest         1.0   NaN        NaN         NaN   
2   45.0        Red   Northeast         1.0   NaN        NaN         NaN   
3   35.0      Blond   Southwest         0.0   NaN        NaN         NaN   
4   33.0      Brown   Southwest         0.0   NaN        NaN         NaN   
5   35.0      Brown   Northeast         0.0   NaN        NaN         NaN   
6   25.0      Black   Southwest         0.0   NaN        NaN         NaN   
7   52.0      Brown   Southeast         0.0   NaN        NaN         NaN   
8   21.0      Blond   Southwest         1.0   NaN        NaN         NaN   
9    NaN        NaN         NaN         NaN  24.0      Blond   Northeast   
10   NaN        NaN         NaN         NaN  48.0      Black   Southwest   
11   NaN        NaN         NaN         NaN  22.0      Black   Southwest   
12   NaN        NaN         NaN         NaN  27.0      Brown   Northeast   
13   NaN        NaN         NaN         NaN  28.0      Black   Southeast   
14   NaN        NaN         NaN         NaN  21.0      Blond   Southeast   
15   NaN        NaN         NaN         NaN  51.0      Black   Northwest   
16   NaN        NaN         NaN         NaN  23.0      Brown   Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0

In [171]:
pd.concat([df5,df6],axis=1,ignore_index=False)

Age Hair Color U.S. Region  Validation   Age Hair Color U.S. Region  \
0   25.0      Black   Southwest         1.0   NaN        NaN         NaN   
1   30.0      Black   Northwest         1.0   NaN        NaN         NaN   
2   45.0        Red   Northeast         1.0   NaN        NaN         NaN   
3   35.0      Blond   Southwest         0.0   NaN        NaN         NaN   
4   33.0      Brown   Southwest         0.0   NaN        NaN         NaN   
5   35.0      Brown   Northeast         0.0   NaN        NaN         NaN   
6   25.0      Black   Southwest         0.0   NaN        NaN         NaN   
7   52.0      Brown   Southeast         0.0   NaN        NaN         NaN   
8   21.0      Blond   Southwest         1.0   NaN        NaN         NaN   
9    NaN        NaN         NaN         NaN  24.0      Blond   Northeast   
10   NaN        NaN         NaN         NaN  48.0      Black   Southwest   
11   NaN        NaN         NaN         NaN  22.0      Black   Southwest   
12   NaN        NaN         NaN         NaN  27.0      Brown   Northeast   
13   NaN        NaN         NaN         NaN  28.0      Black   Southeast   
14   NaN        NaN         NaN         NaN  21.0      Blond   Southeast   
15   NaN        NaN         NaN         NaN  51.0      Black   Northwest   
16   NaN        NaN         NaN         NaN  23.0      Brown   Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0