1.	Create a program that asks the user to enter their name and their age. Print out a message that tells them the year that they will turn 100 years old

In [1]:
import pandas as pd
import numpy as np

In [5]:
# Get the user input using the input function
# create a funtion to calculate the years for 100
name=input("Enter the Name:")
age=int(input("Enter the Age:"))

def years_for_100(name,age):
    age_for_100=100-age
    print(f"{name}: will be 100 years old in {age_for_100} years")
    return age_for_100

years_for_100(name,age)

Enter the Name:Naga
Enter the Age:36
Naga: will be 100 years old in 64 years


64

2.	What is pandas groupby? Demonstrate with your own example

In [6]:
# We will load the sample excel data using the auto sample file
# let us first read the file
df=pd.read_csv(r"C:\Users\ADMIN\Desktop\auto1.csv")

In [7]:
df.shape

(205, 27)

In [15]:
df["fuel_type"].value_counts()

gas       185
diesel     20
Name: fuel_type, dtype: int64

In [18]:
df.groupby(['make','fuel_type'])['price'].count()

make           fuel_type
alfa-romero    gas           3
audi           gas           6
bmw            gas           8
chevrolet      gas           3
dodge          gas           9
honda          gas          13
isuzu          gas           2
jaguar         gas           3
mazda          diesel        2
               gas          15
mercedes-benz  diesel        4
               gas           4
mercury        gas           1
mitsubishi     gas          13
nissan         diesel        1
               gas          17
peugot         diesel        5
               gas           6
plymouth       gas           7
porsche        gas           4
renault        gas           2
saab           gas           6
subaru         gas          12
toyota         diesel        3
               gas          29
volkswagen     diesel        4
               gas           8
volvo          diesel        1
               gas          10
Name: price, dtype: int64

In [26]:
df.groupby(['make','fuel_type'])['price','city_mpg'].mean()

C:\Users\ADMIN\AppData\Local\Temp/ipykernel_9860/528917835.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['make','fuel_type'])['price','city_mpg'].mean()


price   city_mpg
make          fuel_type                         
alfa-romero   gas        15498.333333  20.333333
audi          gas        17859.166667  18.857143
bmw           gas        26118.750000  19.375000
chevrolet     gas         6007.000000  41.000000
dodge         gas         7875.444444  28.000000
honda         gas         8184.692308  30.384615
isuzu         gas         8916.500000  31.000000
jaguar        gas        34600.000000  14.333333
mazda         diesel     14569.500000  33.500000
              gas        10130.666667  24.666667
mercedes-benz diesel     28394.000000  22.000000
              gas        38900.000000  15.000000
mercury       gas        16503.000000  19.000000
mitsubishi    gas         9239.769231  24.923077
nissan        diesel      7099.000000  45.000000
              gas        10610.764706  25.941176
peugot        diesel     15797.000000  26.800000
              gas        15232.500000  18.833333
plymouth      gas         7963.428571  28.142857
porsche       gas        31400.500000  17.400000
renault       gas         9595.000000  23.000000
saab          gas        15223.333333  20.333333
subaru        gas         8541.250000  26.333333
toyota        diesel      8794.666667  34.000000
              gas         9998.689655  26.827586
volkswagen    diesel      9777.500000  36.000000
              gas        10227.500000  24.875000
volvo         diesel     22470.000000  26.000000
              gas        17622.500000  20.700000

3.	How to create a dataframe from list?

In [28]:
# Let us create a list 
list1=[["Naga",36,"Chennai"],["Alex",32,"Chennai"],["Balu",28,'Cochin']]

In [31]:
# we can create a dataframe from the list using the pandas Dataframe function, define the c
df_list=pd.DataFrame(list1,columns=["Name","Age","Location"])

In [32]:
df_list

Name  Age Location
0  Naga   36  Chennai
1  Alex   32  Chennai
2  Balu   28   Cochin

4.	What are the ways to combine the dataframe in pandas. Give an example for each

In [33]:
df.shape

(205, 27)

In [34]:
df1=df[:100]

In [35]:
df2=df[101:]

In [36]:
df1.shape

(100, 27)

In [37]:
df2.shape

(104, 27)

In [45]:
# we can combine using the append function
df3=df1.append(df2,ignore_index=True)

In [46]:
df3.shape

(204, 27)

#### Using the Concat Function

In [49]:
pd.concat([df1,df2],ignore_index=True,axis=0).shape

(204, 27)

In [51]:
pd.concat([df1,df2],ignore_index=True,axis=1).shape

(204, 54)

#### Using the Merge Function

In [54]:
df1.merge(df2,on='make').shape

(66, 53)

In [55]:
df1.merge(df2,on='make',how='left').shape

(155, 53)

5.	What is the difference between list and tuples in Python?

In [57]:
list1=[1,2,4,5,"abc",[55,44,77,88],True]

In [58]:
# Hashable
list1[2]

4

In [59]:
# mutable
list1[4]='def'

In [60]:
list1

[1, 2, 4, 5, 'def', [55, 44, 77, 88], True]

In [66]:
list1.append(77)

In [67]:
list1

[1, 2, 4, 5, 'def', [55, 44, 77, 88], True, 77]

In [68]:
# Now we will create a tuple
tuple1=(1,3,5,7,8,9,[1,2,3])

In [69]:
tuple1

(1, 3, 5, 7, 8, 9, [1, 2, 3])

In [72]:
# Please note that when we try to extend the list, it is throwing errors
tuple1[2]=55

TypeError: 'tuple' object does not support item assignment

6.	Find out the mean, median and standard deviation of this numpy array -> np.array([1,5,3,100,4,48])

In [78]:
array1=np.array([1,5,3,100,4,48])

In [76]:
array1.mean()

26.833333333333332

In [82]:
np.median(array1)

4.5

In [83]:
np.std(array1)

36.59424666377065

7.	How will you remove duplicate elements from a list?

In [93]:
list1=[1,1,2,3,5,5,5,7,7]

In [87]:
# we can convert the list to a set which will remove the duplicates in a list and we can again reconvert it to a list.
list2=list(set(list1))
list2

[1, 2, 3, 5, 7]

In [89]:
# There are multiple other ways to remove duplicates from list
# we can use dict.fromkeys approach, as fromkeys will take only distinct keys

list3=list(dict.fromkeys(list1))

In [119]:
temp = []


In [120]:
temp

[]

In [121]:
[temp.append(i) for i in list1 if i not in temp ]

[None, None, None, None, None]

In [122]:
temp

[1, 2, 3, 5, 7]

In [123]:
type(temp)

list

#### 8.	What is a map() function in Python? Give an example

In [ ]:
#### Map function is used to apply a expression to all the values in the List/Tuple

In [12]:
list12 = [1,2,3,4,5,6,7,8,9,10]
tuple2 = (5,6,7,8,9)
set2={10,20,30,40,50}

In [9]:
# Example 1 : Map function to increment all the values in the tuple by 10
list(map(lambda x:x+10 , tuple2))

[15, 16, 17, 18, 19]

In [15]:
# Example 2 : Map function to increment all the values in the set by multiplying by 10
list(map(lambda x:x*10 , set2))

[500, 200, 400, 100, 300]

In [16]:
# Example 3: The Filter function will filters the list/tuple elements based on the filter criteria
list(filter(lambda x:x>6 , tuple2))

[7, 8, 9]

#### 9.	What is pass in Python?

In [18]:
# Pass is a placeholder in Python
help("pass")

The "pass" statement
********************

   pass_stmt ::= "pass"

"pass" is a null operation — when it is executed, nothing happens. It
is useful as a placeholder when a statement is required syntactically,
but no code needs to be executed, for example:

   def f(arg): pass    # a function that does nothing (yet)

   class C: pass       # a class with no methods (yet)



In [24]:
# we can define a function with a placeholder, so when executed it just allocates a memory space for the function but no action takes place
def func1():
    pass


In [23]:
# when you execute func1, it just returns the placeholder
func1

<function __main__.func1()>

10.	What is vstack() in numpy? Give an example

#### vstack is used to vertically stack an array && hstack is used to horizontally stack an array

In [30]:
import numpy as np
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[110,120,130],[140,150,160]])

In [31]:
np.vstack((arr1,arr2))

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [110, 120, 130],
       [140, 150, 160]])

In [32]:
np.hstack((arr1,arr2))

array([[ 10,  20,  30, 110, 120, 130],
       [ 40,  50,  60, 140, 150, 160]])

In [33]:
np.vstack((arr2,arr1))

array([[110, 120, 130],
       [140, 150, 160],
       [ 10,  20,  30],
       [ 40,  50,  60]])